version: '2'
services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    network_mode: "host"  
    command: sh -c "python manage.py sync_cassandra && python manage.py runserver 10.0.12.65:8000"
    environment: 
      - DEBUG=1
      - SECRET_KEY=rx9%qisad36g+qf7r75b_0+r9wb20krzyor-t8ken81a#e$h%j
  grafana:
    network_mode: "host"
    image: grafana/grafana:7.5.7
    user: "104"
