version: '2'
services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    network_mode: "host"  
    command: sh -c "python manage.py runserver 10.0.12.65:8000"
    environment: 
      - DEBUG=0
  grafana:
    network_mode: "host"
    image: grafana/grafana:7.5.7
    user: "104"
