version: '2'
networks:
  cassandra:  # docker network where all cassandra nodes will be put in
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DEBUG=0
  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    user: "104"
volumes:
  cassandra_data:
    driver: local