from DBoT.DB import DB
from Parser.JsonParser import JsonParser
import time

DB_Obj = DB('pitest')
Parser_Obj = JsonParser()

start_timeP = time.time()
flat_j1 = Parser_Obj.read_json('Json_Examples\Json1.json')
flat_j2 = Parser_Obj.read_json('Json_Examples\Json2.json')
flat_j3 = Parser_Obj.read_json('Json_Examples\Json3.json')
flat_j4 = Parser_Obj.read_json('Json_Examples\Json4.json')
flat_j5 = Parser_Obj.read_json('Json_Examples\Json5.json')
flat_j6 = Parser_Obj.read_json('Json_Examples\Json6.json')
flat_j7 = Parser_Obj.read_json('Json_Examples\Json7.json')
flat_j8 = Parser_Obj.read_json('Json_Examples\Json8.json')
flat_j9 = Parser_Obj.read_json('Json_Examples\Json9.json')
flat_j10 = Parser_Obj.read_json('Json_Examples\Json10.json')
flat_j11 = Parser_Obj.read_json('Json_Examples\Json11.json')
flat_j12 = Parser_Obj.read_json('Json_Examples\Json12.json')
flat_j13 = Parser_Obj.read_json('Json_Examples\Json13.json')
flat_j14 = Parser_Obj.read_json('Json_Examples\Json14.json')
flat_j15 = Parser_Obj.read_json('Json_Examples\Json15.json')
flat_j16 = Parser_Obj.read_json('Json_Examples\Json16.json')
flat_j17 = Parser_Obj.read_json('Json_Examples\Json17.json')
flat_j18 = Parser_Obj.read_json('Json_Examples\Json18.json')
flat_j19 = Parser_Obj.read_json('Json_Examples\Json19.json')
flat_j20 = Parser_Obj.read_json('Json_Examples\Json20.json')
flat_j21 = Parser_Obj.read_json('Json_Examples\Json21.json')
finish_timeP = time.time()
print("Parsing --- %s seconds ---" % (finish_timeP - start_timeP))

start_timeI = time.time()
DB_Obj.insertIntoSensor(flat_j1, 1, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j2, 2, 1, "Luis")
DB_Obj.insertIntoSensor(flat_j3, 3, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j4, 4, 3, "Luis")
DB_Obj.insertIntoSensor(flat_j5, 5, 1, "Luis")
DB_Obj.insertIntoSensor(flat_j6, 6, 4, "Luis")
#DB_Obj.insertIntoSensor(flat_j7, 7, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j8, 8, 4, "Luis")
DB_Obj.insertIntoSensor(flat_j9, 9, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j10, 10, 1, "Luis")
DB_Obj.insertIntoSensor(flat_j11, 11, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j12, 12, 10, "Luis")
#DB_Obj.insertIntoSensor(flat_j13, 13, 1, "Luis")
DB_Obj.insertIntoSensor(flat_j14, 14, 18, "Luis")
DB_Obj.insertIntoSensor(flat_j15, 15, 21, "Luis")
#DB_Obj.insertIntoSensor(flat_j16, 16, 1, "Luis")
#DB_Obj.insertIntoSensor(flat_j17, 17, 21, "Luis")
#DB_Obj.insertIntoSensor(flat_j18, 18, 12, "Luis")
#DB_Obj.insertIntoSensor(flat_j19, 19, 18, "Luis")
#DB_Obj.insertIntoSensor(flat_j20, 20, 21, "Luis")
#DB_Obj.insertIntoSensor(flat_j21, 21, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j20, 22, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j19, 23, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j18, 24, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j17, 25, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j16, 26, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j15, 27, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j14, 28, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j15, 29, 1, "Luis")
#DB_Obj.insertIntoSensor(flat_j14, 30, 3, "Luis")
finish_timeI = time.time()
print("Inserting --- %s seconds ---" % (finish_timeI - start_timeI))

start_time1 = time.time()
queryResult1 = DB_Obj.query('table1', ['timestamp'], {'temperature': '>11', 'sensorid': '=0002'})
finish_time1 = time.time()

start_time2 = time.time()
queryResult2 = DB_Obj.queryPerUser('Luis', ['*'], {'sensorid': '=0001'})
finish_time2 = time.time()

start_time3 = time.time()
queryResult3 = DB_Obj.queryPerSensor('Marta', '2', ['*'], {'temperature': '=12'})
finish_time3 = time.time()

start_time4 = time.time()
queryResult4 = DB_Obj.query('table1', ['*'], {'temperature': '=12'})
finish_time4 = time.time()

print("\n")
print(queryResult1)
print("Query Complex --- %s seconds ---" % (finish_time1 - start_time1))
print("\n")
print(queryResult2)
print("Query User --- %s seconds ---" % (finish_time2 - start_time2))
print("\n")
print(queryResult3)
print("Query Sensor --- %s seconds ---" % (finish_time3 - start_time3))
print("\n")
print(queryResult4)
print("Query Simple --- %s seconds ---" % (finish_time4 - start_time4))