from DBoT.DB import DB
from Parser.JsonParser import JsonParser
import time

DB_Obj = DB('pitest')
Parser_Obj = JsonParser()

start_timeP = time.time()
flat_j1 = Parser_Obj.read_json('Json_Examples\Json1.json')
flat_j2 = Parser_Obj.read_json('Json_Examples\Json2.json')
flat_j3 = Parser_Obj.read_json('Json_Examples\Json3.json')
flat_j4 = Parser_Obj.read_json('Json_Examples\Json4.json')
flat_j5 = Parser_Obj.read_json('Json_Examples\Json5.json')
flat_j6 = Parser_Obj.read_json('Json_Examples\Json6.json')
flat_j7 = Parser_Obj.read_json('Json_Examples\Json7.json')
flat_j8 = Parser_Obj.read_json('Json_Examples\Json8.json')
flat_j9 = Parser_Obj.read_json('Json_Examples\Json9.json')
flat_j10 = Parser_Obj.read_json('Json_Examples\Json10.json')
flat_j11 = Parser_Obj.read_json('Json_Examples\Json11.json')
flat_j12 = Parser_Obj.read_json('Json_Examples\Json12.json')
flat_j13 = Parser_Obj.read_json('Json_Examples\Json13.json')
flat_j14 = Parser_Obj.read_json('Json_Examples\Json14.json')
flat_j15 = Parser_Obj.read_json('Json_Examples\Json15.json')
flat_j16 = Parser_Obj.read_json('Json_Examples\Json16.json')
flat_j17 = Parser_Obj.read_json('Json_Examples\Json17.json')
flat_j18 = Parser_Obj.read_json('Json_Examples\Json18.json')
flat_j19 = Parser_Obj.read_json('Json_Examples\Json19.json')
flat_j20 = Parser_Obj.read_json('Json_Examples\Json20.json')
flat_j21 = Parser_Obj.read_json('Json_Examples\Json21.json')
finish_timeP = time.time()
print("Parsing --- %s seconds ---" % (finish_timeP - start_timeP))

start_timeI = time.time()
DB_Obj.insertIntoSensor(flat_j1, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j2, 1, "Luis")
DB_Obj.insertIntoSensor(flat_j3, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j4, 3, "Luis")
DB_Obj.insertIntoSensor(flat_j5, 1, "Luis")
DB_Obj.insertIntoSensor(flat_j6, 4, "Luis")
DB_Obj.insertIntoSensor(flat_j7, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j8, 4, "Luis")
DB_Obj.insertIntoSensor(flat_j9, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j10, 1, "Luis")
DB_Obj.insertIntoSensor(flat_j11, 2, "Marta")
DB_Obj.insertIntoSensor(flat_j12, 10, "Luis")
DB_Obj.insertIntoSensor(flat_j13, 1, "Luis")
#DB_Obj.insertIntoSensor(flat_j14, 18, "Luis")
#DB_Obj.insertIntoSensor(flat_j15, 21, "Luis")
#DB_Obj.insertIntoSensor(flat_j16, 1, "Luis")
#DB_Obj.insertIntoSensor(flat_j17, 21, "Luis")
#DB_Obj.insertIntoSensor(flat_j18, 12, "Luis")
#DB_Obj.insertIntoSensor(flat_j19, 18, "Luis")
#DB_Obj.insertIntoSensor(flat_j20, 21, "Luis")
#DB_Obj.insertIntoSensor(flat_j21, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j20, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j19, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j18, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j17, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j16, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j15, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j14, 2, "Marta")
#DB_Obj.insertIntoSensor(flat_j15, 1, "Luis")
#DB_Obj.insertIntoSensor(flat_j14, 3, "Luis")
finish_timeI = time.time()
print("Inserting --- %s seconds ---" % (finish_timeI - start_timeI))

start_time1 = time.time()
queryResult1 = DB_Obj.query('table1', ['timestamp'], {'temperature': '>11', 'sensorid': '=0002'})
finish_time1 = time.time()

start_time2 = time.time()
queryResult2 = DB_Obj.queryPerUser('Luis', ['*'], {'sensorid': '=0001'})
finish_time2 = time.time()

start_time3 = time.time()
queryResult3 = DB_Obj.queryPerSensor('Marta', '2', ['*'], {'temperature': '=12'})
finish_time3 = time.time()

start_time4 = time.time()
queryResult4 = DB_Obj.query('table1', ['*'], {'temperature': '=12'})
finish_time4 = time.time()

start_time5 = time.time()
queryResult5 = DB_Obj.queryPerUser('Luis', ['AVG:temperature'], {'sensorid': '=0001'})
finish_time5 = time.time()

start_time6 = time.time()
queryResult6 = DB_Obj.queryPerUser('Luis', ['MIN:temperature'], {'sensorid': '=0001'})
finish_time6 = time.time()

start_time7 = time.time()
queryResult7 = DB_Obj.queryPerUser('Luis', ['MAX:temperature'], {'sensorid': '=0001'})
finish_time7 = time.time()

start_time8 = time.time()
queryResult8 = DB_Obj.queryPerUser('Luis', ['SUM:temperature'], {'sensorid': '=0001'})
finish_time8 = time.time()

start_time9 = time.time()
queryResult9 = DB_Obj.queryPerUser('Luis', ['CNT:temperature'], {'sensorid': '=0001'})
finish_time9 = time.time()

print("\n")
DB.printResults(queryResult1)
print("Query Complex --- %s seconds ---" % (finish_time1 - start_time1))
print("\n")
DB.printResults(queryResult2)
print("Query User --- %s seconds ---" % (finish_time2 - start_time2))
print("\n")
DB.printResults(queryResult3)
print("Query Sensor --- %s seconds ---" % (finish_time3 - start_time3))
print("\n")
DB.printResults(queryResult4)
print("Query Simple --- %s seconds ---" % (finish_time4 - start_time4))
print("\n")
DB.printResults(queryResult5)
print("Query Average --- %s seconds ---" % (finish_time5 - start_time5))
print("\n")
DB.printResults(queryResult6)
print("Query Minimum --- %s seconds ---" % (finish_time6 - start_time6))
print("\n")
DB.printResults(queryResult7)
print("Query Maximum --- %s seconds ---" % (finish_time7 - start_time7))
print("\n")
DB.printResults(queryResult8)
print("Query Sum --- %s seconds ---" % (finish_time8 - start_time8))
print("\n")
DB.printResults(queryResult9)
print("Query Count --- %s seconds ---" % (finish_time9 - start_time9))