# Generated by Django 3.1 on 2020-08-29 19:38

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', columns.Text(primary_key=True)),
                ('user', columns.Text(primary_key=True, clustering_order="DESC")),
                ('tables',columns.List(value_type=columns.Text)),
                ('pks',columns.List(value_type=columns.Text)),

            ],
        ),
    ]
